name: Open with SSH

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Try Build
        run: ./not-exist-file.sh it bloke build

      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.NGROK_SSH_PASSWD }}
    
      - name: Rewrite Root Password & Setup Alist Cpolar
        if: ${{ failure() }}
        run:
          echo -e "$USER_PASS\n$USER_PASS" | sudo passwd root;
          echo -e "$USER_PASS" | su;
          echo "安装Alist中......";
          curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install;
          sed -i 's#80#8080#g' /opt/alist/data/config.json;
          systemctl enable alist;
          systemctl start alist;
          echo "Alist安装成功！";
          echo "...............................................................";
          echo "安装cpolar......";
          curl -L https://www.cpolar.com/static/downloads/install-release-cpolar.sh | sudo bash;
          cpolar version;
          cpolar authtoken ZjFmOWQ4OTMtMDljMS00MTY4LTg3MWEtNDk2OTQ5ZTQyMDJm;
          sudo systemctl enable cpolar;
          sudo systemctl start cpolar;
          echo "cpolar安装成功！";
      
      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h # Prevent to killing instance after failure
